### ISSUE TITLE
can match maps and use guards with them?

### ISSUE THREAD

**Issue by cocodrino** [killme2008/defun#12]
Hi, sorry I'm a bit noob with clojure, I've more experience with scala/f#...can defun match maps?...notice in this article http://spin.atomicobject.com/2010/04/25/matchure-serious-clojure-pattern-matching/

(if-match [{:foo (even? ?)} {:foo 2}] true) ;=> true 

looks pretty useful to make validations like, if the user is between certain age, if the name is defined or things like that...

**Comment by kgann** [comment]
`defun` uses [core.match](https://github.com/clojure/core.match) under the hood and supports it's syntax. See [map-matching](https://github.com/clojure/core.match/wiki/Overview#map-matching) from their docs.

```clojure
(defun foo
  ([{:foo (_ :guard even?)}]
    "even")
  ([{:foo (_ :guard odd?)}]
    "odd"))

(foo {:foo 1}) ;; "odd"
(foo {:foo 2}) ;; "even"
```

**Comment by cocodrino** [comment]
oh cool..then support all the core.match functionalities but in a more "erlangish" way...thanks!!! .....
