### ISSUE TITLE
Single-segment namespace

### ISSUE THREAD

**Issue by weavejester** [killme2008/defun#14]
Would it be possible to change the single-segment namespace `defun` into something like `defun.core` or `defun.macros`?

I realise that defun is a rare case where it might be possible to get away with a single-segment namespace, because the namespace only uses macros and so avoids the usual problems single-segment namespaces have. However, it seems safer and more future-proof to follow the usual conventions around Clojure naming.

**Comment by killme2008** [comment]
Thanks for your advice， it's a good idea,  i will rename the namespace in next release.
