### ISSUE TITLE
Supports clojurescript

### ISSUE THREAD

**Issue by killme2008** [killme2008/defun#5]

**Comment by belucid** [comment]
I'm going to take a stab at it.

**Comment by killme2008** [comment]
@belucid cool,it would be great.
i don't have experience in clojurescript.

**Comment by sander** [comment]
Not a fan of the indentation, but this commit adds cljs support: https://github.com/sander/defun/commit/2d7a1937b0fa1c88817d15f81094ad483b97d4c5

**Comment by belucid** [comment]
@sander can you put it in a PR so @killme2008 can incorporate it?

**Comment by killme2008** [comment]
@sander Yep, please create a pull request, i will test it,thanks a lot, great work.

**Comment by killme2008** [comment]
@sander @belucid  Releases 0.3.0-alpha, looks great, thanks a lot.
